### ISSUE TITLE
About 15 seconds in I error out

### ISSUE THREAD

**Issue by BlueScreenBuddy** [corngood/kill-ryzen-win#5]
Before I run off to try to RMA want to ensure that this indicates a a possible segfault:

```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Exception: FAIL
   at kill_ryzen_win.Program.<>c__DisplayClass0_0.<Main>b__0(Int32 x) in C:\Users\Jason\Desktop\kill ryzen\Program.cs:line 43
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at kill_ryzen_win.Program.Main(String[] args) in C:\Users\Jason\Desktop\kill ryzen\Program.cs:line 51
```

**Comment by corngood** [comment]
Do you get any more output above that?  Do you get a windows error reporting box when it fails?

If you do get an error reporting box, and you have a debugger installed, you can attach and look at the callstack.  If it matches the one in https://github.com/corngood/kill-ryzen-win/issues/1 then it's almost certainly the same problem I was having.

Another thing you can do is try disabling authenticode by setting the registry key `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Safer\CodeIdentifiers\AuthenticodeEnabled`.  For me that stops the test from crashing, so if it makes the test work for you then that also indicates the same problem.

We've been ghosted by AMD on the RMA we opened for this problem, and I've just been running with authenticode disabled.  I still think there's an underlying OS or hardware problem, but it hasn't got enough attention for them to address it.  I'd love to know if it's been fixed in TR, epyc, or raven ridge, but I don't have any to test.

**Comment by BlueScreenBuddy** [comment]
I got a few lines of "bzip2.c" and then that error. I did not get the error reporting box. I ran it again. Here's a full screenshot https://vgy.me/Sbm6EN.png

**Comment by corngood** [comment]
That does look like the same problem, since it ran for a little while successfully before failing.  I would still try disabling authenticode to see if it's more stable.

**Comment by corngood** [comment]
Oh, also, which CPU do you have exactly?

**Comment by BlueScreenBuddy** [comment]
Ok I disabled authenticode and re-ran it on my 1800x at stock settings.  Kept running for about 1 hour with no issues before I manually ended it.

**Comment by corngood** [comment]
Ok, thanks for trying that.  You're certainly seeing the same problem I have.  I've been running with authenticode disabled, and the system seems fairly stable.  Just keep an eye out for it turning itself back on after reboots and system updates.  Also I suppose you are losing some security features.

I'd love to know if you get anywhere with an RMA.  We've had replacement chips from AMD and they didn't solve this problem.  AMD confirmed that they could reproduce it, but we haven't heard anything since, and that was the end of last year.

**Comment by BlueScreenBuddy** [comment]
I ran a linux kill script and got this: https://vgy.me/qDtgiV.png

**Comment by corngood** [comment]
Sorry for the delay.  Yeah, that looks like it's failing as well... Our (launch window) processors were failing in both linux and windows, but the RMA ones only fail on windows.

**Comment by kikijiki** [comment]
Enabling AuthenticodeEnabled makes the test fail even on a 2700x...

**Comment by corngood** [comment]
@kikijiki Well shit, I was hoping to buy one of those, but I'm hesitant until I know more about what's causing this.

Which MB are you using?

**Comment by kikijiki** [comment]
Asus Crosshair VI Hero, latest bios.
